'use client'

import { useState } from 'react'
import { Copy, Check, RefreshCw, ArrowRight } from 'lucide-react'
import { ContextEntry } from '@/lib/contextStorage'

interface Props {
  entries: ContextEntry[]
  savedText: string | undefined
  onSave: (text: string) => void
  onSendToChat: (text: string) => void
}

function buildMarkdown(entries: ContextEntry[]): string {
  const lines: string[] = ['# Contexte Professionnel\n']
  entries.forEach(entry => {
    lines.push(`## ${entry.label}`)
    lines.push(`*${getPrompt(entry.type, entry.label)}*\n`)
    lines.push(entry.transcript || '*Aucun contexte enregistré.*')
    lines.push('\n---\n')
  })
  return lines.join('\n')
}

function getPrompt(type: ContextEntry['type'], label: string): string {
  switch (type) {
    case 'profile': return 'Décrivez-vous en quelques minutes : qui vous êtes, ce que vous faites, vos forces, ce que vous recherchez.'
    case 'skills': return 'Quelles sont vos compétences clés ? Dans quels domaines excellez-vous ?'
    case 'aspirations': return "Qu'est-ce que vous recherchez dans votre prochain poste ? Qu'aimez-vous dans votre travail ?"
    case 'qualities': return 'Quelles sont vos qualités principales ? Comment les personnes qui vous connaissent bien vous décrivent-elles ?'
    case 'flaws': return "Quels sont vos défauts ou axes d'amélioration ? Comment travaillez-vous pour les surmonter ?"
    case 'education': {
      const school = label.includes('@') ? label.split('@').pop()?.trim() : label
      return `Parlez de cette formation chez ${school} : contenu, ce que vous en avez retenu, compétences acquises.`
    }
    case 'experience': {
      const company = label.includes('@') ? label.split('@').pop()?.trim().split('·')[0].trim() : label
      return `Parlez de votre expérience chez ${company} : missions, réalisations, contexte, difficultés surmontées.`
    }
  }
}

export default function ContextFileView({ entries, savedText, onSave, onSendToChat }: Props) {
  const autoGenerated = buildMarkdown(entries)
  // editText: user's in-progress edits (null = no unsaved changes)
  const [editText, setEditText] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  // Derived display: unsaved edit > last saved > auto-generated from slots
  const displayText = editText ?? savedText ?? autoGenerated
  const isDirty = editText !== null

  function handleSave() {
    if (editText !== null) onSave(editText)
    setEditText(null)
  }

  function handleRegenerate() {
    onSave(autoGenerated)
    setEditText(null)
  }

  function handleCopy() {
    navigator.clipboard.writeText(displayText).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 1800)
    })
  }

  function handleSendToChat() {
    const message = `[Contexte vocal complet]\n\n${displayText}\n\nAnalyse mon contexte personnel et compare-le avec mon CV. Fais-en une analyse de mon profil complet, identifie les écarts entre ce que je dis de moi et ce qui est écrit dans le CV, et propose des améliorations concrètes du CV basées sur ce contexte.`
    onSendToChat(message)
  }

  return (
    <div className="flex-1 flex flex-col overflow-hidden">
      {/* Toolbar — ligne 1 : actions d'édition */}
      <div className="px-4 pt-2.5 pb-2 border-b border-[#E5E4E0] flex flex-col gap-2 shrink-0">
        <div className="flex items-center justify-between gap-2">
          <p className="text-[11px] font-body text-[#9D9C98] leading-snug">
            Toutes vos réponses en Markdown — éditez, copiez, ou injectez dans l&apos;IA.
          </p>
          <div className="flex items-center gap-1.5 shrink-0">
            {isDirty && (
              <button
                onClick={handleRegenerate}
                className="flex items-center gap-1 px-2 py-1 rounded text-[11px] font-body text-[#9D9C98] hover:text-[#1A1A18] hover:bg-[#F4F3F0] transition-colors"
                title="Régénérer depuis les slots"
              >
                <RefreshCw size={10} />
                Réinitialiser
              </button>
            )}
            {isDirty && (
              <button
                onClick={handleSave}
                className="px-2.5 py-1 rounded-md bg-[#1B4332] text-white text-[11px] font-body font-medium hover:bg-[#163A2B] transition-colors"
              >
                Sauvegarder
              </button>
            )}
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 px-2.5 py-1 rounded-md border border-[#CCCBC6] text-[11px] font-body text-[#6B6A66] hover:bg-[#F4F3F0] transition-colors"
            >
              {copied ? <Check size={10} className="text-[#1B4332]" /> : <Copy size={10} />}
              {copied ? 'Copié !' : 'Copier'}
            </button>
          </div>
        </div>
        {/* CTA principal — envoyer tout dans le chat */}
        <button
          onClick={handleSendToChat}
          className="w-full flex items-center justify-center gap-1.5 py-2 rounded-md bg-[#1B4332] text-white text-xs font-body font-medium hover:bg-[#163A2B] transition-colors"
        >
          Envoyer dans le chat pour analyse
          <ArrowRight size={12} />
        </button>
      </div>

      {/* Textarea */}
      <textarea
        value={displayText}
        onChange={e => setEditText(e.target.value)}
        spellCheck={false}
        className="flex-1 resize-none px-4 py-3 text-[12px] font-mono text-[#1A1A18] bg-[#FAFAF8] focus:outline-none leading-relaxed"
        style={{ minHeight: 0 }}
      />
    </div>
  )
}
